version: '3.8'

services:
  # Web UI Service
  trading-agents-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplified-trading-agents
    ports:
      - "8000:8000"
    environment:
      # These will be loaded from .env file
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - FMP_API_KEY=${FMP_API_KEY:-}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-}
      # LangSmith (optional - for tracing and monitoring)
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT:-https://api.smith.langchain.com}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY:-}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-trading-agents}
    env_file:
      - .env
    volumes:
      # Mount analysis cache for persistence
      - ./ui/analysis_cache:/app/ui/analysis_cache
      - ./analysis:/app/analysis
    restart: unless-stopped
    networks:
      - trading-agents-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # CLI Service (optional - for running analyses via CLI)
  trading-agents-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplified-trading-agents-cli
    environment:
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - FMP_API_KEY=${FMP_API_KEY:-}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-}
      # LangSmith (optional)
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-false}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT:-https://api.smith.langchain.com}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY:-}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-trading-agents}
    env_file:
      - .env
    volumes:
      - ./analysis:/app/analysis
    networks:
      - trading-agents-network
    command: ["python", "main.py", "--ticker", "NVDA"]
    profiles:
      - cli  # Only start when explicitly requested

networks:
  trading-agents-network:
    driver: bridge

volumes:
  analysis-cache:
  analysis-results:
